version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: sh -c "python -m celery_app.web && sleep 5"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - db_data:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis

  celery_worker:
    build: .
    command: sh -c "sleep 10 && celery -A celery_app.tasks worker --loglevel=info"
    volumes:
      - .:/app
      - db_data:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    command: sh -c "sleep 10 && celery -A celery_app.tasks beat --loglevel=info"
    volumes:
      - .:/app
      - db_data:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  celery_exporter:
    image: danihodovic/celery-exporter:latest
    command: --broker-url=redis://redis:6379/0 --enable-events
    ports:
      - "9808:9808"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  redis_data:
  db_data:
